//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAppHabLat.MyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Claim
    {
        public int Id_Claim { get; set; }
        public int Id_Speciality { get; set; }
        public int Id_Dicipline { get; set; }
    
        public virtual Dicipline Dicipline { get; set; }
        public virtual Speciality Speciality { get; set; }
    }
}
