//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationAppHabLat.MyBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Id_Exam { get; set; }
        public Nullable<System.DateTime> Date_Exam { get; set; }
        public int Code_Discipline { get; set; }
        public int Reg_Number { get; set; }
        public int Tab_Number { get; set; }
        public string Auditory { get; set; }
        public Nullable<int> Grade { get; set; }
    
        public virtual Dicipline Dicipline { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
